USE mini_board;

CREATE TABLE boards (
	NO					INT				NOT NULL 	PRIMARY KEY AUTO_INCREMENT
	,title			VARCHAR(100)	NOT NULL
	,content			VARCHAR(1000)	NOT NULL
	,created_at		DATETIME			NOT NULL		DEFAULT	CURRENT_TIMESTAMP()
	,update_at		DATETIME			NOT NULL		DEFAULT	CURRENT_TIMESTAMP()
	,deleted_at		DATETIME		
);